### ISSUE TITLE
Service Page not responding

### ISSUE THREAD

**Issue by ebenwatts** [vitodeploy/vito#139]
After updating to VITO v1.1.0, I realized my service page started giving error 505. Please can you fix it ASAP?

Services I have available:
1. phpMyadmin
2. Nginx
3. Php
4. Mysql
5. Redis
6. Supervisor
7. UFW

<img width="612" alt="Screenshot 2024-03-27 at 3 12 42 PM" src="https://github.com/vitodeploy/vito/assets/17008209/22579f94-151e-4454-aed6-c023c0f46e8e">

**Comment by saeedvaziry** [comment]
This is a breaking change from converting PHPMyAdmin from service to site.
Steps to resolve it:

First delete the `phpmyadmin` service from the `services` table.

Then:

```
rm -rf /home/vito/phpmyadmin

sudo rm /etc/nginx/sites-available/phpmyadmin

sudo rm /etc/nginx/sites-enabled/phpmyadmin

sudo service nginx restart
```

**Comment by devsarfo** [comment]
@ebenwatts to solve this, you need to remove **phpmyadmin** from your services table. 

Because the v1.x uses SQLite instead of MySQL, you will need **tinker** to do this.

`cd /home/vito/YOUR-VITO-DOMAIN`

`php artisan tinker`

After the tinker console opens you run the following commands to delete all records from the services table where the type column equals "phpmyadmin".

`DB::delete("DELETE FROM services WHERE type = ?", ['phpmyadmin']);`

You can also specify the server_id if you want to remove it for a specific server

`DB::delete("DELETE FROM services WHERE server_id = ? AND type = ?", [SERVER-ID, 'phpmyadmin']);`

This should solve your problem. 

Note: If you had phpmMyAdmin installed, it will still run.

**Comment by ebenwatts** [comment]
@devsarfo Thanks a lot, everything is working perfectly now
