### ISSUE TITLE
Ability to create site without connecting to source control

### ISSUE THREAD

**Issue by louis-l** [vitodeploy/vito#92]
Hi,

First of all, thanks for the awesome work. I have been looking for something like this for ages.

I wanted to create a site without using source control, because I want to use PHP Deployer to achieve zero downtime deployment. However, the GUI does not allow me to leave these fields blank:
![image](https://github.com/vitodeploy/vito/assets/10172565/caaf54f0-d88a-4ca6-a08b-69c96f3f9c14)

Wonder if it is possible to alter the creating new site behaviour a little bit so that users only enter minimal necessary info (e.g. site name, domain, PHP version, directory). The rest can be filled or set as a option/setting.

Cheers,
Louis

**Comment by saeedvaziry** [comment]
Thanks @louis-l  for the feedback,
PHP Deployer is a command line at the end as far as I know, And VitoDeploy enables you to handle your deployment by providing a deployment script. so a workaround to this would be to design the deployment script of Vito in a way that it runs the PHP Deployer and deploys your app.

**Comment by louis-l** [comment]
Hi @saeedvaziry,

That was my plan, and I wanted to use Github Actions to run PHP Deployer script. Therefore, setting up source control in Vito panel is redundant in this case.

I also found this feature request: https://vitodeploy.featurebase.app/submissions/659872b2e9bba33a9a1d2e4b 
Would be good to have that.

While we are here, I have couple questions related to the deployment:

1. do you have examples of how to write deploy script? I checked out https://vitodeploy.com/sites/application.html#deploy but not much info there.
2. does Vito support zero downtime deployment (for sites)? 
3. if I want to achieve zero downtime deployment, what do you reckon the best approach from here (from Vito)?

Cheers,
Louis

**Comment by saeedvaziry** [comment]
I see the point,
I think having a new site time `Blank PHP` without any requirements for source control should fix the problem here.

regarding the questions:
1. first you will need to create the site via a source control which I think will not work for you
2. vito does not support zero deployment but I believe it is just a script that makes a deployment to be happen in zero time (there is ways to do it I think)
3. for a zero downtime with script for example you can copy the project directory and run the deployment on the copied one and once it is done replace it with the original one.

anyway, will put the blank php site on prio as many people need that also.

**Comment by louis-l** [comment]
Thank you very much @saeedvaziry 
Appreciate it 🙏

**Comment by saeedvaziry** [comment]
Added the feature. If you have the Vito instance, Just update it

https://vitodeploy.com/introduction/update.html

**Comment by louis-l** [comment]
Woo, that was quick.
Tested and works like a charm. 
Tyvm 🙏
